// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestRoomApi.Data;

#nullable disable

namespace QuestRoomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestRoomApi.Models.AboutInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mission");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vision");

                    b.HasKey("Id");

                    b.ToTable("about_info");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<int>("ExtraParticipantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("extra_participants_count");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Aggregator")
                        .HasColumnType("text")
                        .HasColumnName("aggregator");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("participants_count");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<string>("PromoCode")
                        .HasColumnType("text")
                        .HasColumnName("promo_code");

                    b.Property<Guid?>("PromoCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promo_code_id");

                    b.Property<int?>("PromoDiscountAmount")
                        .HasColumnType("integer")
                        .HasColumnName("promo_discount_amount");

                    b.Property<string>("PromoDiscountType")
                        .HasColumnType("text")
                        .HasColumnName("promo_discount_type");

                    b.Property<int?>("PromoDiscountValue")
                        .HasColumnType("integer")
                        .HasColumnName("promo_discount_value");

                    b.Property<Guid?>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<Guid?>("QuestScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("QuestScheduleId")
                        .IsUnique();

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("QuestRoomApi.Models.BookingExtraService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid?>("QuestExtraServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_extra_service_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("booking_extra_services");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("certificates");
                });

            modelBuilder.Entity("QuestRoomApi.Models.CertificateOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id");

                    b.Property<string>("CertificateTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("text")
                        .HasColumnName("delivery_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("certificate_orders");
                });

            modelBuilder.Entity("QuestRoomApi.Models.DurationBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("badge_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.ToTable("duration_badges");
                });

            modelBuilder.Entity("QuestRoomApi.Models.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.HasKey("Id");

                    b.ToTable("image_assets");
                });

            modelBuilder.Entity("QuestRoomApi.Models.ProductionCalendarDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DayType")
                        .HasColumnType("text")
                        .HasColumnName("day_type");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("boolean")
                        .HasColumnName("is_holiday");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("production_calendar_days");
                });

            modelBuilder.Entity("QuestRoomApi.Models.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_type");

                    b.Property<int>("DiscountValue")
                        .HasColumnType("integer")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.ToTable("promo_codes");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_text");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_mode");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("ShowDescription")
                        .HasColumnType("boolean")
                        .HasColumnName("show_description");

                    b.Property<bool>("ShowDiscountText")
                        .HasColumnType("boolean")
                        .HasColumnName("show_discount_text");

                    b.Property<bool>("ShowImage")
                        .HasColumnType("boolean")
                        .HasColumnName("show_image");

                    b.Property<bool>("ShowPeriod")
                        .HasColumnType("boolean")
                        .HasColumnName("show_period");

                    b.Property<bool>("ShowTitle")
                        .HasColumnType("boolean")
                        .HasColumnName("show_title");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Addresses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("addresses");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("age_rating");

                    b.Property<string>("AgeRestriction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("age_restriction");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("DifficultyMax")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_max");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<int>("ExtraParticipantPrice")
                        .HasColumnType("integer")
                        .HasColumnName("extra_participant_price");

                    b.Property<int>("ExtraParticipantsMax")
                        .HasColumnType("integer")
                        .HasColumnName("extra_participants_max");

                    b.Property<string>("GiftGameLabel")
                        .HasColumnType("text")
                        .HasColumnName("gift_game_label");

                    b.Property<string>("GiftGameUrl")
                        .HasColumnType("text")
                        .HasColumnName("gift_game_url");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("images");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("MainImage")
                        .HasColumnType("text")
                        .HasColumnName("main_image");

                    b.Property<int>("ParticipantsMax")
                        .HasColumnType("integer")
                        .HasColumnName("participants_max");

                    b.Property<int>("ParticipantsMin")
                        .HasColumnType("integer")
                        .HasColumnName("participants_min");

                    b.PrimitiveCollection<string[]>("Phones")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("phones");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("quests");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestExtraService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("quest_extra_services");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestPricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<int[]>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("days_of_week");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.PrimitiveCollection<Guid[]>("QuestIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("quest_ids");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("quest_pricing_rules");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_booked");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_slot");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "Date", "TimeSlot")
                        .IsUnique();

                    b.ToTable("quest_schedule");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "Date")
                        .IsUnique();

                    b.ToTable("quest_schedule_overrides");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleOverrideSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_id");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_slot");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OverrideId", "TimeSlot")
                        .IsUnique();

                    b.ToTable("quest_schedule_override_slots");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("HolidayPrice")
                        .HasColumnType("integer")
                        .HasColumnName("holiday_price");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.ToTable("quest_schedule_settings");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestWeeklySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_slot");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "DayOfWeek", "TimeSlot")
                        .IsUnique();

                    b.ToTable("quest_weekly_slots");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("QuestTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quest_title");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("review_date");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rules");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BackgroundGradientFrom")
                        .HasColumnType("text")
                        .HasColumnName("background_gradient_from");

                    b.Property<string>("BackgroundGradientTo")
                        .HasColumnType("text")
                        .HasColumnName("background_gradient_to");

                    b.Property<string>("BackgroundGradientVia")
                        .HasColumnType("text")
                        .HasColumnName("background_gradient_via");

                    b.Property<int>("BookingCutoffMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("booking_cutoff_minutes");

                    b.Property<int>("BookingDaysAhead")
                        .HasColumnType("integer")
                        .HasColumnName("booking_days_ahead");

                    b.Property<string>("BookingEmailTemplateAdmin")
                        .HasColumnType("text")
                        .HasColumnName("booking_email_template_admin");

                    b.Property<string>("BookingEmailTemplateCustomer")
                        .HasColumnType("text")
                        .HasColumnName("booking_email_template_customer");

                    b.Property<string>("BookingStatusCancelledColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_cancelled_color");

                    b.Property<string>("BookingStatusCompletedColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_completed_color");

                    b.Property<string>("BookingStatusConfirmedColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_confirmed_color");

                    b.Property<string>("BookingStatusCreatedColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_created_color");

                    b.Property<string>("BookingStatusNotConfirmedColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_not_confirmed_color");

                    b.Property<string>("BookingStatusPendingColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_pending_color");

                    b.Property<string>("BookingStatusPlannedColor")
                        .HasColumnType("text")
                        .HasColumnName("booking_status_planned_color");

                    b.Property<string>("CertificateEmailTemplateAdmin")
                        .HasColumnType("text")
                        .HasColumnName("certificate_email_template_admin");

                    b.Property<string>("CertificateEmailTemplateCustomer")
                        .HasColumnType("text")
                        .HasColumnName("certificate_email_template_customer");

                    b.Property<string>("CertificatePageDescription")
                        .HasColumnType("text")
                        .HasColumnName("certificate_page_description");

                    b.Property<string>("CertificatePagePricing")
                        .HasColumnType("text")
                        .HasColumnName("certificate_page_pricing");

                    b.Property<string>("CertificatePageTitle")
                        .HasColumnType("text")
                        .HasColumnName("certificate_page_title");

                    b.Property<string>("CertificateStatusCanceledColor")
                        .HasColumnType("text")
                        .HasColumnName("certificate_status_canceled_color");

                    b.Property<string>("CertificateStatusCompletedColor")
                        .HasColumnType("text")
                        .HasColumnName("certificate_status_completed_color");

                    b.Property<string>("CertificateStatusPendingColor")
                        .HasColumnType("text")
                        .HasColumnName("certificate_status_pending_color");

                    b.Property<string>("CertificateStatusProcessedColor")
                        .HasColumnType("text")
                        .HasColumnName("certificate_status_processed_color");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GiftGameLabel")
                        .HasColumnType("text")
                        .HasColumnName("gift_game_label");

                    b.Property<string>("GiftGameUrl")
                        .HasColumnType("text")
                        .HasColumnName("gift_game_url");

                    b.Property<string>("InstagramIconBackground")
                        .HasColumnType("text")
                        .HasColumnName("instagram_icon_background");

                    b.Property<string>("InstagramIconColor")
                        .HasColumnType("text")
                        .HasColumnName("instagram_icon_color");

                    b.Property<string>("InstagramIconUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_icon_url");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_url");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("text")
                        .HasColumnName("notification_email");

                    b.Property<bool>("NotifyBookingAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_booking_admin");

                    b.Property<bool>("NotifyBookingCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_booking_customer");

                    b.Property<bool>("NotifyCertificateAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_certificate_admin");

                    b.Property<bool>("NotifyCertificateCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_certificate_customer");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("PromotionsPerRow")
                        .HasColumnType("integer")
                        .HasColumnName("promotions_per_row");

                    b.Property<string>("ReviewsFlampEmbed")
                        .HasColumnType("text")
                        .HasColumnName("reviews_flamp_embed");

                    b.Property<string>("ReviewsMode")
                        .HasColumnType("text")
                        .HasColumnName("reviews_mode");

                    b.Property<string>("ScheduleBackground")
                        .HasColumnType("text")
                        .HasColumnName("schedule_background");

                    b.Property<string>("SmtpFromEmail")
                        .HasColumnType("text")
                        .HasColumnName("smtp_from_email");

                    b.Property<string>("SmtpFromName")
                        .HasColumnType("text")
                        .HasColumnName("smtp_from_name");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text")
                        .HasColumnName("smtp_host");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("text")
                        .HasColumnName("smtp_password");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_port");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("boolean")
                        .HasColumnName("smtp_use_ssl");

                    b.Property<string>("SmtpUser")
                        .HasColumnType("text")
                        .HasColumnName("smtp_user");

                    b.Property<string>("TelegramIconBackground")
                        .HasColumnType("text")
                        .HasColumnName("telegram_icon_background");

                    b.Property<string>("TelegramIconColor")
                        .HasColumnType("text")
                        .HasColumnName("telegram_icon_color");

                    b.Property<string>("TelegramIconUrl")
                        .HasColumnType("text")
                        .HasColumnName("telegram_icon_url");

                    b.Property<string>("TelegramUrl")
                        .HasColumnType("text")
                        .HasColumnName("telegram_url");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VideoModalEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("video_modal_enabled");

                    b.Property<string>("VkIconBackground")
                        .HasColumnType("text")
                        .HasColumnName("vk_icon_background");

                    b.Property<string>("VkIconColor")
                        .HasColumnType("text")
                        .HasColumnName("vk_icon_color");

                    b.Property<string>("VkIconUrl")
                        .HasColumnType("text")
                        .HasColumnName("vk_icon_url");

                    b.Property<string>("VkUrl")
                        .HasColumnType("text")
                        .HasColumnName("vk_url");

                    b.Property<string>("YoutubeIconBackground")
                        .HasColumnType("text")
                        .HasColumnName("youtube_icon_background");

                    b.Property<string>("YoutubeIconColor")
                        .HasColumnType("text")
                        .HasColumnName("youtube_icon_color");

                    b.Property<string>("YoutubeIconUrl")
                        .HasColumnType("text")
                        .HasColumnName("youtube_icon_url");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("text")
                        .HasColumnName("youtube_url");

                    b.HasKey("Id");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("QuestRoomApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Booking", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuestRoomApi.Models.QuestSchedule", "QuestSchedule")
                        .WithOne("Booking")
                        .HasForeignKey("QuestRoomApi.Models.Booking", "QuestScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Quest");

                    b.Navigation("QuestSchedule");
                });

            modelBuilder.Entity("QuestRoomApi.Models.BookingExtraService", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Booking", "Booking")
                        .WithMany("ExtraServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestExtraService", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany("ExtraServices")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestPricingRule", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestSchedule", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleOverride", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleOverrideSlot", b =>
                {
                    b.HasOne("QuestRoomApi.Models.QuestScheduleOverride", "Override")
                        .WithMany("Slots")
                        .HasForeignKey("OverrideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Override");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleSettings", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestWeeklySlot", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestRoomApi.Models.User", b =>
                {
                    b.HasOne("QuestRoomApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Booking", b =>
                {
                    b.Navigation("ExtraServices");
                });

            modelBuilder.Entity("QuestRoomApi.Models.Quest", b =>
                {
                    b.Navigation("ExtraServices");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestSchedule", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("QuestRoomApi.Models.QuestScheduleOverride", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
