namespace QuestRoomApi.DTOs.Content;

public class SettingsDto
{
    public Guid Id { get; set; }
    public string? VkUrl { get; set; }
    public string? YoutubeUrl { get; set; }
    public string? InstagramUrl { get; set; }
    public string? TelegramUrl { get; set; }
    public string? VkIconUrl { get; set; }
    public string? VkIconColor { get; set; }
    public string? VkIconBackground { get; set; }
    public string? YoutubeIconUrl { get; set; }
    public string? YoutubeIconColor { get; set; }
    public string? YoutubeIconBackground { get; set; }
    public string? InstagramIconUrl { get; set; }
    public string? InstagramIconColor { get; set; }
    public string? InstagramIconBackground { get; set; }
    public string? TelegramIconUrl { get; set; }
    public string? TelegramIconColor { get; set; }
    public string? TelegramIconBackground { get; set; }
    public string? Address { get; set; }
    public string? Email { get; set; }
    public string? NotificationEmail { get; set; }
    public string? SmtpHost { get; set; }
    public int? SmtpPort { get; set; }
    public string? SmtpUser { get; set; }
    public string? SmtpPassword { get; set; }
    public bool SmtpUseSsl { get; set; }
    public string? SmtpFromEmail { get; set; }
    public string? SmtpFromName { get; set; }
    public bool NotifyBookingAdmin { get; set; }
    public bool NotifyBookingCustomer { get; set; }
    public string? BookingEmailTemplateAdmin { get; set; }
    public string? BookingEmailTemplateCustomer { get; set; }
    public bool NotifyCertificateAdmin { get; set; }
    public bool NotifyCertificateCustomer { get; set; }
    public string? CertificateEmailTemplateAdmin { get; set; }
    public string? CertificateEmailTemplateCustomer { get; set; }
    public string? Phone { get; set; }
    public string? LogoUrl { get; set; }
    public string? GiftGameLabel { get; set; }
    public string? GiftGameUrl { get; set; }
    public string? CertificatePageTitle { get; set; }
    public string? CertificatePageDescription { get; set; }
    public string? CertificatePagePricing { get; set; }
    public string? ReviewsMode { get; set; }
    public string? ReviewsFlampEmbed { get; set; }
    public string? BookingStatusPlannedColor { get; set; }
    public string? BookingStatusCreatedColor { get; set; }
    public string? BookingStatusPendingColor { get; set; }
    public string? BookingStatusNotConfirmedColor { get; set; }
    public string? BookingStatusConfirmedColor { get; set; }
    public string? BookingStatusCompletedColor { get; set; }
    public string? BookingStatusCancelledColor { get; set; }
    public string? CertificateStatusPendingColor { get; set; }
    public string? CertificateStatusProcessedColor { get; set; }
    public string? CertificateStatusCompletedColor { get; set; }
    public string? CertificateStatusCanceledColor { get; set; }
    public int BookingDaysAhead { get; set; }
    public int BookingCutoffMinutes { get; set; }
    public string? TimeZone { get; set; }
    public int PromotionsPerRow { get; set; }
    public int TeaZonesPerRow { get; set; }
    public bool VideoModalEnabled { get; set; }
    public string? BackgroundGradientFrom { get; set; }
    public string? BackgroundGradientVia { get; set; }
    public string? BackgroundGradientTo { get; set; }
    public string? ScheduleBackground { get; set; }
    public string? MirKvestovMd5Key { get; set; }
    public string? MirKvestovPrepayMd5Key { get; set; }
    public string? MirKvestovSlotIdFormat { get; set; }
    public int MirKvestovScheduleDaysAhead { get; set; }
    public List<string> MirKvestovScheduleFields { get; set; } = new();
    public bool MirKvestovApiLoggingEnabled { get; set; }
    public DateTime UpdatedAt { get; set; }
}
